; Main CPU address 1
CPU1=192.168.92.55
; Main CPU address 2 Leave empty if spatial redundancy is not used
; CPU2 192.168.92.52
CPU2=
; TCP port to connect to
Port=2533
; Working directory
WorkingDir=C:\Temp\EACC\Files
; Enable data logging in a file
Logging=1
; Enable Debug messages on console
Debugging=1
; Ticket Printing on console
CDRPrint =1
; Beep on Ticket received
CDRBeep=0
